#!/usr/bin/env python3
"""Build dictionary/index.md from entry files."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRIES = ROOT / "dictionary" / "entries"
INDEX = ROOT / "dictionary" / "index.md"


def parse_frontmatter(text: str) -> dict[str, str | list[str]]:
    end = text.find("\n---\n", 4)
    data: dict[str, str | list[str]] = {}
    current_key = None
    for raw in text[4:end].splitlines():
        line = raw.rstrip()
        if line.startswith("  - ") and current_key:
            data.setdefault(current_key, [])
            assert isinstance(data[current_key], list)
            data[current_key].append(line[4:].strip())
            continue
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
        if not match:
            continue
        key, value = match.groups()
        current_key = key
        data[key] = [] if value == "" else value.strip().strip('"')
    return data


def first_definition(text: str) -> str:
    body = text.split("\n---\n", 2)[-1]
    lines = [line.strip() for line in body.splitlines()]
    for line in lines:
        if line and not line.startswith("#") and not line.startswith("---"):
            return line
    return "No definition yet."


def main() -> int:
    rows = []
    for path in sorted(ENTRIES.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        meta = parse_frontmatter(text)
        word = str(meta.get("word", path.stem))
        status = str(meta.get("status", "unknown"))
        roots = meta.get("roots", [])
        if isinstance(roots, list):
            roots_text = " + ".join(roots)
        else:
            roots_text = str(roots)
        rows.append((word.lower(), word, roots_text, status, path.name, first_definition(text)))

    out = [
        "# Wombology Dictionary Index",
        "",
        "Generated by `scripts/build-index.py`.",
        "",
        "| Word | Roots | Status | Definition |",
        "| --- | --- | --- | --- |",
    ]
    for _, word, roots, status, filename, definition in sorted(rows):
        out.append(f"| [{word}](entries/{filename}) | {roots} | {status} | {definition} |")
    out.append("")
    INDEX.write_text("\n".join(out), encoding="utf-8")
    print(f"built {INDEX} with {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
